#!/bin/sh -e

export PREFIX=""
if [ -d "venv" ]; then
  export PREFIX="venv/bin/"
fi

set -x

scripts/build

${PREFIX}pip uninstall hello-unasync --yes
${PREFIX}pip install --find-links=dist hello-unasync

scripts/clean
