#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

if [ -z $CI ]; then
    scripts/check
fi

scripts/compile

export PYTEST_ADDOPTS="--cov=$(find venv -type d -name hello_unasync)"
${PREFIX}pytest $@
